### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by KennethSimJingHong** [manu-urba/dart-covid19-api#1]
Im trying to grab the covid data by country "Malaysia", somehow the latest data shown is two days ago. Eg. today date is 14 November but latest data only contain 12 November. However, its really a great api XD keep your good work.

**Comment by manu-urba** [comment]
Hello, thank you very much!
Which method are you using to retrieve the data?
It looks like both direct API call and this package are fetching the data correctly, here's a correct example of a working code I just made:
```dart
import 'package:covid19/covid19.dart';

void main() async {
  var covid = Covid19Client();
  var data = await covid.getByCountry(country: 'Malaysia');
  print(data[data.length - 1].date);
  covid.close();
}
// Output: 2020-11-13T00:00:00Z
```

Direct API call: http://prntscr.com/vj2u1d
Everything seems correct here too: https://github.com/CSSEGISandData/COVID-19/commits/master

**Comment by KennethSimJingHong** [comment]
> Hello, thank you very much!
> Which method are you using to retrieve the data?
> It looks like both direct API call and this package are fetching the data correctly, here's a correct example of a working code I just made:
> 
> ```dart
> import 'package:covid19/covid19.dart';
> 
> void main() async {
>   var covid = Covid19Client();
>   var data = await covid.getByCountry(country: 'Malaysia');
>   print(data[data.length - 1].date);
>   covid.close();
> }
> // Output: 2020-11-13T00:00:00Z
> ```
> 
> Direct API call: http://prntscr.com/vj2u1d
> Everything seems correct here too: https://github.com/CSSEGISandData/COVID-19/commits/master

var data = await covid.getByCountry(country: 'Malaysia');
My problem is the last array of the "data" is not latest covid data of current date but either one or two days before, and it takes quite some time to be updated.
But i'm good with it and thank you so much.
