### ISSUE TITLE
[ INVALID ] getDayOne() 

### ISSUE THREAD

**Issue by NesaByte** [manu-urba/dart-covid19-api#4]
Hi, when I was working on the Tests on the example/example1.dart (issue #2) I found out that the function getDayOne() returns:

```dart
    List<Covid19CountryAllStatus> list = List();

    for (var i in data) {
      list.add(
        Covid19CountryAllStatus(
          country: i['Country'],
          countryCode: i['CountryCode'],
          province: i['Province'],
          city: i['City'],
          cityCode: i['CityCode'],
          lat: i['Lat'],
          lon: i['Lon'],
          confirmed: i['Confirmed'],
          deaths: i['Deaths'],
          recovered: i['Recovered'],
          active: i['Active'],
          date: i['Date'],
        ),
      );
    }
    return list;
```

However, when we look at the API that this function is calling, it looks like this:

```json
[{"Country":"Canada","CountryCode":"CA","Province":"Ontario","City":"","CityCode":"","Lat":"51.25","Lon":"-85.32","Cases":1,"Status":"confirmed","Date":"2020-01-26T00:00:00Z"},
```
As you can see, we need to take in the list of:
 - country
 - countryCode
 - province
 - city
 - cityCode
 - lat
 - lon
 - **cases**
 - **status**
 - date

In your current list, the users might call for "deaths", "recovered", or "active" and this will result to a null because they do not exist in the API. 

![image](https://user-images.githubusercontent.com/53501261/100554205-1aeeb480-3261-11eb-9d91-afb531d3286d.png)
the test above results to:
![image](https://user-images.githubusercontent.com/53501261/100554215-2e018480-3261-11eb-9f67-69adbb17ce05.png)

I want to fix this, please assign this to me. thank you

**Comment by manu-urba** [comment]
I didn't even notice this! Thank you.
