### ISSUE TITLE
[ New Function ] getWorld()

### ISSUE THREAD

**Issue by NesaByte** [manu-urba/dart-covid19-api#6]
I want to add a new function to your application.

As you take your API from [COVID POSTMAN](https://documenter.getpostman.com/view/10808728/SzS8rjbc#c4b075a4-83b2-4a98-9db9-b3be51fa6bef), I want to cover the endpoint: 
![image](https://user-images.githubusercontent.com/53501261/100673120-e5b19780-3330-11eb-8d54-b808b0afbac9.png)

To be able to implement this, I will add a class called CountryCases and add the function getWorld().

Please assign me.

**Comment by manu-urba** [comment]
Thank you!
